### ISSUE TITLE
Multivariate TS classification

### ISSUE THREAD

**Issue by zeisal** [benfulcher/hctsa#36]
Dear Ben,
first of all thank you for all the work and effort you put into the hctsa package. It has been really helpful so far!

In the beginning I was dealing with a single sensor to monitor a pressure ts. The classification is mostly a 2-class but can also be a multiple class problem. 
Now, I have multiple sensors available that monitor one and the same process. I would like to include possible relations and dependencies between the sampled variables into my analsis. Therefore, I like to ask if you have made any experience yet on how to implement a multivariate ts analysis in a smart way, still using all the beautiful functions within this package.

Thank you in advance and best regards,
Alex

**Comment by benfulcher** [comment]
Thanks Alex for the kind words and glad you're enjoying _hctsa_ :smile:
_hctsa_ is designed for univariate time-series analysis, so there is no native support for the types of multivariate analyses your mention.
You have some options:
1. Append lots of univariate feature matrices together (so that features of each univariate time series are captured). [you may wish to do some dimensionality reduction in this case]
2. Add some features of multivariate dependencies manually.
Neither of these options are natively supported at this stage, but you could use _hctsa_ simply as a way to compute the feature matrix, that you then analyze yourself externally.
Hope this helps,
Ben

**Comment by zeisal** [comment]
Thank you Ben for your quick reply.
I thought about the same. Since I used the reduced feature set of only ~220 features I still have an overseeable matrix even with multiple ts. 
I also came across the question on why you selected especially those features for the reduced set. Is this from your experience or how did you select them? 
Best regards, Alex

**Comment by benfulcher** [comment]
Hi Alex,
The reduced feature set of 220 is very rough and outdated.
See [here](https://github.com/chlubba/catch22) for an updated pipeline on this topic (and [associated paper](https://doi.org/10.1007/s10618-019-00647-x)).
Best,
Ben
