### ISSUE TITLE
TS_InitiateParallel passes incorrect information to BF_CheckToolBox

### ISSUE THREAD

**Issue by anthonyjsexton** [benfulcher/hctsa#76]
The function TS_InitiateParallel calls BF_CheckToolBox using the argument 'distrib_computing_toolbox' on [line 40](https://github.com/benfulcher/hctsa/blob/3e76975eef0380060385e8379ffe988fb89d44ab/PeripheryFunctions/TS_InitiateParallel.m#L40) but BF_CheckToolBox uses 'parallel_computing_toolbox'.

However, when I change the code in my local version of hctsa and try to use parallel computing, TS_Compute starts to throw errors for a number of functions
- 'Use of MEX functions is not supported on a thread-based worker..'
- 'Unable to find or import 'com.mathworks.addons_common.notificationframework.InstalledAddOnsCache'. Imported names must end with '.*' or be fully qualified..'
- 'Use of function system is not supported on a thread-based worker..'
- 'Use of function javaObject is not supported on a thread-based worker..'

I don't know if this is a local install problem.

**Comment by benfulcher** [comment]
Thanks for the clear message. I typically test in serial, since for such an embarrassingly parallel computing problem like this, it tends to be simpler to distribute serial computation jobs across many individual cores, than parallel jobs across multiple local cores (cf. https://github.com/benfulcher/distributed_hctsa). But I will assign this to take another look at to make sure the option of local parallelization remains well maintained.

**Comment by FixItChris** [comment]
After changing the code I've gotten it to work on my machine - the other issues could be an installation problem?

**Comment by benfulcher** [comment]
Seems resolvable after merging the latest PR
